### ISSUE TITLE
Adjust notification size with javascript

### ISSUE THREAD

**Issue by hmz777** [caroso1222/notyf#89]
As you can see from the photo below, large content doesn't play well with notyf because the notification container's width is limited to 400px.
![chrome_0uhLcWWhFY](https://user-images.githubusercontent.com/38891601/96282453-70d60880-0fe3-11eb-88bb-83900cb216f6.png)

Which is fixable using the `className` option, but now the ripple effect is broken because it's also set to 400px

Can we add an option to specify the `max-width` of the container which would also be applied to the ripple element?
Something like this:
```javascript
notyf.error({
                duration: duration,
                position: position,
                dismissible: dismissible,
                message: ErrorMessage,
                max-width: '50em'
            });
```
The code below (scss) fixes the problem by overriding default styles:
```scss
//A custom class applied via className option.
.toast-custom-notyf {
    max-width: 50em !important;

    .notyf__ripple {
        height: 50em;
        width: 50em;
    }
}
```
And renders the following result:
![8HnVttDoLF](https://user-images.githubusercontent.com/38891601/96283259-9ca5be00-0fe4-11eb-841c-c0b1226586a1.gif)

And great job on this library, i love it!
